# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pinapp-client-mobile' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Auth0 Lock

    pod 'Lock', '~> 1.26'
    pod 'Lock/TouchID'
    pod 'Lock/SMS'
    pod 'Lock/Email'

    target 'pinapp-client-mobileTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
